#[path = "create-addressbook.rs"]
pub mod create_addressbook;
#[path = "create-card.rs"]
pub mod create_card;
#[path = "delete-addressbook.rs"]
pub mod delete_addressbook;
#[path = "delete-card.rs"]
pub mod delete_card;
#[path = "list-addressbooks.rs"]
pub mod list_addressbooks;
#[path = "list-cards.rs"]
pub mod list_cards;
#[path = "read-card.rs"]
pub mod read_card;
#[path = "update-addressbook.rs"]
pub mod update_addressbook;
#[path = "update-card.rs"]
pub mod update_card;
